### PR TITLE
Streaming requests for Net::HTTP

### PR DESCRIPTION
**Pull request by grosser**
Based on work by @bmaddy, @james-lawrence and @ANorwell
https://github.com/backupify/faraday/tree/streaming-0.9.0
https://github.com/bmaddy/faraday/tree/streaming

rebased https://github.com/lostisland/faraday/pull/461

### CODE REVIEW

**Comment by nightscape** [comment]
Hi @grosser, any reason why you closed this PR and deleted your branch?
Could we help anything to make this happen?

**Comment by grosser** [comment]
I think I closed this because of the "faraday is dead" talk going on ... would love to get this merged ... since hurley is dead now too maybe faraday can be revived ? :D 

@mislav

**Comment by grosser** [comment]
restored the branch, so feel free to use it ...

**Comment by nightscape** [comment]
I rebased the branch and fixed a spurious error concerning empty chunks:
https://github.com/crealytics/faraday/commits/streaming
I don't know how to best proceed though. Should I create a new PR and you close this one, or do you want to `git reset --hard` your PR to our changes and `git push --force` it over this one?

**Comment by nightscape** [comment]
I rebased the branch and fixed a spurious error concerning empty chunks:
https://github.com/crealytics/faraday/commits/streaming
I don't know how to best proceed though. Should I create a new PR and you close this one, or do you want to `git reset --hard` your PR to our changes and `git push --force` it over this one?

**Comment by grosser** [comment]
I'd prefer if you open a new / clean PR ... atm I don't need this, so I'd
prefer to close mine :)

**Comment by nightscape** [comment]
Ok, new PR at https://github.com/lostisland/faraday/pull/604, also fixing the issue you discovered previously.

**Pull request closed without merging**
