### PR TITLE
:verify_callback ssl option for Net::HTTP adapter

### PR DESCRIPTION
**Pull request by AlexanderPavlenko**
This option is useful for certificate pinning — https://stackoverflow.com/questions/22093042/implementing-https-certificate-pubkey-pinning-with-ruby

### CODE REVIEW

**Comment by thomasgallagher** [comment]
This would be very useful

**Comment by mltsy** [comment]
Yes!  Please :+1:

**Comment by mltsy** [comment]
@AlexanderPavlenko would you be able to add a test for this? @mislav would you merge this very simple feature if it has a test?

**Comment by jimpo** [comment]
Can you also add to the NetHttpPersistent adapter which overrides this method?

**Comment by mltsy** [comment]
Is there a reason Net:HTTP::Persistent overrides the configure_ssl method?  Are some of the config options irrelevant for a persistent connection or something? I can't see why they would be... or is it just to avoid automatically setting `use_ssl = true` for some reason?  I feel like if we make an update to that here, we should remove the redundancy at the same time if possible.

**Comment by mltsy** [comment]
And I will answered my own question: `http.use_ssl = true` is not a thing in Net::HTTP::Persistent.  Maybe it would be better to just move that to its own method (`enable_ssl`) and override that method to do nothing in the Persistent adapter :)  Then all the ssl options (which seem to be identical for both libraries) don't have to be repeated.

**Comment by iMacTia** [comment]
Hi All,

I'm sorry but we're not accepting PR of this type as explained on https://github.com/lostisland/faraday/pull/470#issuecomment-254296415.

You're welcome to share your thoughts on #648

**Pull request closed without merging**
