### PR TITLE
Add EditorConfig file

### PR DESCRIPTION
**Pull request by AlexWayfer**
Resolve issues.

More info here: https://editorconfig.org/

### CODE REVIEW

**Comment by AlexWayfer** [comment]
> we can merge this after RuboCop updates have made the Linting step pass.

Can I track it somewhere or help with it? I see it fails in two different PRs and there is success in `master`.

**Comment by AlexWayfer** [comment]
I'm trying to resolve these issues separately.

**Comment by AlexWayfer** [comment]
Done in #1149.

**Comment by olleolleolle** [comment]
@AlexWayfer I'm going to "Update branch" using this big button and then rebase merge this onto master. Thanks!

**Comment by AlexWayfer** [comment]
> @AlexWayfer I'm going to "Update branch" using this big button and then rebase merge this onto master. Thanks!

I didn't rebase it in time! OK, thank you.

**Comment by olleolleolle** [comment]
@AlexWayfer https://github.com/lostisland/faraday/commits/master the commit turned out fine. ✨

**Pull request merged**
