### PR TITLE
update docs to a httpbingo on example requests and adding webrick for ruby 3.x support

### PR DESCRIPTION
**Pull request by JAugusto42**
## Description
- updating the docs discussed in #1164 
- Update docs gemfile by adding webrick for ruby 3.x jekyll support.

### CODE REVIEW

**Review by olleolleolle — APPROVED** [review]
Thanks, @JAugusto42! This is very helpful 👍.

**Comment by olleolleolle** [comment]
The complaints from Rubocop can be autofixed using the rubocop -A option. Please do that and push the changes, when you get a chance. No rush.

**Comment by JAugusto42** [comment]
yeah, i'm sorry.

**Comment by olleolleolle** [comment]
@JAugusto42 thanks for helping out, it's awesome!

**Review by iMacTia — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
