### PR TITLE
Restrict rake to less than v11, which drops support for older rubies.

### PR DESCRIPTION
**Pull request by sbleon**

### CODE REVIEW

**Comment by sbleon** [comment]
This resolves #570

**Comment by bbozo** [comment]
:+1: it makes tests fail on #564

**Comment by bbozo** [comment]
Note, I added

``` ruby
# Newer versions drop support for Ruby < 1.9.3, but we still support them.
if RUBY_VERSION >= '1.9.3'
  gem 'rake'
else
  gem 'rake', '< 11.0.0'
end
```

into #564 to make the tests pass

**Comment by mislav** [comment]
Thanks @sbleon!!

**Pull request merged**
