### PR TITLE
Typhoeus Compatibility

### PR DESCRIPTION
**Pull request by iMacTia**
## Description
Continuing the work started in #745 and fixing the incompatibility introduced with #715

### CODE REVIEW

**Comment by iMacTia** [comment]
I had to disable 2 tests to make them green with `SSL=yes` one of these tests was skipped even for the internal adapter, the other one seems due to the fact that the adapter managed by Typhoeus doesn't rise a `Faraday::SSLError` but a simple `Faraday::ConnectionFailed`.

However I believe we can safely ignore that test as everyone using typhuoes today is probably using the one provided by the gem, thus has probably never seen this error 😅

**Comment by iMacTia** [comment]
@olleolleolle @philsturgeon green light 👍 ?

**Comment by olleolleolle** [comment]
@iMacTia Yay!

**Comment by iMacTia** [comment]
Thank you guys, merging this in 👍 

@philsturgeon feel free to join us on [Gitter](https://gitter.im/lostisland/faraday?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) for a faster communication 😄

**Pull request merged**
