### PR TITLE
Re-add support for Ruby 2.4+

### LINKED ISSUE #1369: Faraday 1.9 broke the ruby 2.5 compatibility
## Basic Info

* Faraday Version: 1.9.0
* Ruby Version: 2.5.x

## Issue description
Version 1.9.0 bumped the minimum ruby constraint breaking the compatiblity with ruby 2.5
I understand that 2.5 is EOL, but such end of support is equivalent to a breaking change IMHO.
Was the bump of the constraint important/mandatory?
If not, do you think it would be possible to yank/republish a 1.9 version (or a 1.9.1) with 2.5 support?

Thanks in advance

### PR DESCRIPTION
**Pull request by iMacTia**
## Description
Re-add support for Ruby 2.4+
Fixes #1369

### CODE REVIEW

**Review by olleolleolle — APPROVED** [review]
👍

**Comment by iMacTia** [comment]
Will need to re-release `faraday-multipart` and `faraday-retry` to support Ruby 2.4+ or Ruby 2.5+, but I'll leave this for later as it's not as urgent

**Comment by Justin-W** [comment]
> Will need to re-release `faraday-multipart` and `faraday-retry` to support Ruby 2.4+ or Ruby 2.5+, but I'll leave this for later as it's not as urgent

@iMacTia The removal of support for Ruby v2.4 from `faraday-retry` is currently breaking some of our automation. We'd like to see that regression fixed ASAP.

**Comment by ccdredzik** [comment]
@iMacTia It is interesting that some do update their faraday library, but can't do so for the ruby version they're running. 2.4 is dead, so is 2.5. Don't resurrect them.

**Comment by iMacTia** [comment]
I'd normally agree but since I messed up a bit with the releases yesterday and that it didn't cost me much in the end, I re-waded both in a fix release for 1.9.

That said, Faraday 2.0 will not support anything below 2.6 and we will drop EOL'ed support, even on minor version bumps, if it becomes a problem to support them

**Pull request merged**
