### PR TITLE
check proxy exceptions via "no_proxy" environment variable

### PR DESCRIPTION
**Pull request by quake**

### CODE REVIEW

**Comment by kcdragon** [comment]
:thumbsup: I have a server with ElasticSearch hosted locally and have localhost included in the no_proxy list. However, Faraday still sends the request through the proxy defined in http_proxy. This PR fixes the issue by skipping over the proxy since the request is for a URL in no_proxy.

**Comment by narcisobenigno** [comment]
+1 to  it works.

**Comment by raphox** [comment]
Duplicate of #247

**Comment by saily** [comment]
i want to follow up on this, what's missing, can we try to get this merged?

**Comment by LTangaF** [comment]
I'd like to see this done, too.  More of a bug than an enhancement. Everyone kind of expects software to honor the no_proxy settings.

**Comment by iMacTia** [comment]
Management of `no_proxy` is a WIP but has been stale till now.
The implementation of #361 is by far the best one available, so I'm going to close this in favour of that.
You can contribute on that PR if you need this feature in.

**Pull request closed without merging**
