### PR TITLE
cleanup rakefile

### PR DESCRIPTION
**Pull request by grosser**
- generate_certs is used from script/
 - console == bundle console
 - script/package == rake build (unnecessary since release takes care of it)
 - script/release == rake release
 - script/cached-bundle == obsolete, travis does it automatically

@mislav

### CODE REVIEW

**Comment by grosser** [comment]
@mislav you around ... anyone else maintaining this project ?

**Comment by technoweenie** [comment]
Big :-1: Having the explicit scripts in there is precisely the point: http://githubengineering.com/scripts-to-rule-them-all/. Now, I'm sure some of them can be cleaned up. If `script/release` is simply just `bin/rake release` or something, that's fine.

Also, re: Faraday maintenance: https://github.com/lostisland/faraday/issues/454

**Comment by grosser** [comment]
@mislav can we make this Hurley thing official then ... did not know Faraday was dead :/

**Comment by mislav** [comment]
I've merged just the other good stuff but kept our explicit `script/release`. Thanks!

**Pull request closed without merging**
