### PR TITLE
Add log scrubbing feature

### PR DESCRIPTION
**Pull request by petems**
Added a feature to use a regex parameter to scrub data from logs.

I implemented it in a similar way to what's being done in https://github.com/lostisland/faraday/pull/277

Fixes https://github.com/lostisland/faraday/issues/282 :+1:

### CODE REVIEW

**Comment by Linuus** [comment]
@mislav Any progress here?

**Comment by petems** [comment]
So I've learnt a lot about clean git commits since I submitted this, I've rebased with master and cleaned up the implementation.

Any thoughts?

**Comment by petems** [comment]
Ok, the tests no longer work, will need help o nthat!

**Comment by Linuus** [comment]
@petems  you don't have any `filter` method. You need to define one that adds the filter to the `@filter` instance variable.

I tried to fix it for you but I haven't been able to make the tests pass. The logger is called twice in my tests, once with the filter and once without.

```
Finished in 0.003971s, 251.8024 runs/s, 1007.2096 assertions/s.

  1) Failure:
Adapters::LoggerTest#test_logs_filter_url [test/adapters/logger_test.rb:93]:
Expected /foo/ to not match "I, [2016-01-15T18:58:34.531688 #46317]  INFO -- : get http:/foo\nI, [2016-01-15T18:58:34.531831 #46317]  INFO -- : get http:/[REDACTED]\n"
```

Weird :)

**Comment by iMacTia** [comment]
Hi @petems, are you still willing to contribute with this PR? It has been blocked for some time now.

**Comment by iMacTia** [comment]
Tried to manual-merge but as @Linuus said the latest commit is missing the `Faraday::Response::Logge#filter` method.

Closing but happy to reopen in case someone wants to contribute :)

**Comment by petems** [comment]
@iMacTia Yeah, it's been a few years, I think in one of my rebases I lost the main logic! D'oh!

I'm digging through my reflog and trying to fix it now 👍

**Comment by iMacTia** [comment]
That would be great! If you can just provide the missing method I can try to put it into the rebased branch and check if tests are passing :)

**Comment by petems** [comment]
@iMacTia Awesome! Done in #650, hopefully we can get this merged soon, this was my first ever big PR for a gem I use a lot, it's been my white whale to get it merged at some point 👍

**Pull request closed without merging**
