### PR TITLE
Added retry block option to retry middleware.

### PR DESCRIPTION
**Pull request by borsothy**
## Description
Added `retry_blk` option to the retry middleware, so you can set a block which is executed after every retry.

## Todos
List any remaining work that needs to be done, i.e:
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by borsothy** [comment]
Please let me know if you like the idea, and how it could be improved.

**Comment by borsothy** [comment]
The usecase we want this for is sending a metric/report after every retry to an external service, so we can alert if there's a spike in retries.

Addressed your comments, thanks for the feedback :)

**Comment by borsothy** [comment]
Absolutely, actually I just realised I only need `env`, but I can absolutely extend the block parameters.

**Comment by iMacTia** [comment]
Cool, I noticed you've also updated the description to point out the 4 parameters.
Looks good now and all tests are green 👍 
LGTM

**Pull request merged**
