### PR TITLE
Allow JSON and IO in the same payload

### PR DESCRIPTION
**Pull request by jeremy-israel**
## Description
This PR aims to make it possible to multipart POST an IO and a JSON payload at the same time.
Fixes https://github.com/lostisland/faraday/issues/769

## Additional Notes
Example of API which requires this :
https://developer.concur.com/api-reference/receipts/endpoints.html#endpoint-post-a-receipt

cURL data and image:

```
curl -v -k -X POST https://us.api.concursolutions.com/receipts/v4/users/{USER ID FROM YOUR ID TOKEN} \
-H "Authorization: Bearer {YOUR ACCESS TOKEN}" \
-H "Content-Type:multipart/form-data" \
-H "link: <http://schema.concursolutions.com/{VALIDATION SCHEMA FROM SCHEMA ENDPOINT}.schema.json>;rel=describedBy" \
-F "receipt=<{PATH TO YOUR RECEIPT JSON};type=application/json" \
-F "image=@{PATH TO YOUR IMAGE};type={FILE MIME TYPE OF YOUR IMAGE}"
```

### CODE REVIEW

**Comment by technoweenie** [comment]
Gah, I merged this on accident when I was trying to provide some feedback.

I would prefer supporting something like this when defining the payload on the client:

```ruby
      {
        json_content: Faraday::UploadIO.new(json_content, 'applicaton/json'),
        io_content: Faraday::UploadIO.new(io_content, 'application/pdf')
      }
```

That doesn't quite work because `json_content` is being treated as a file path because it's not an IO object. One workaround is to wrap it in a StringIO, which only fails the filename check on the json part in the added specs.


```ruby
      {
        json_content: Faraday::UploadIO.new(StringIO.new(json_content), 'applicaton/json'),
        io_content: Faraday::UploadIO.new(io_content, 'application/pdf')
      }
```

I prefer this approach, since it's not specific to json, and allows the user to opt-in (as @iMacTia said above).

**Comment by technoweenie** [comment]
Oh, I should've made this more clear. I'm not suggesting that `Faraday::UploadIO.new` is the answer here. My suggestion right now is more along the lines of:

```ruby
{
  json_content: SOMETHING(json_content, 'application/json')
}
```

I'm not sure what `SOMETHING` should be yet.

**Comment by jeremy-israel** [comment]
@technoweenie I'll try to make it work the way you suggest and open another PR.

**Comment by technoweenie** [comment]
Sounds good. I'm re-familiarizing myself with this part of the codebase. I'm also open to new class or method names than `Faraday::UploadIO.new`. It should be possible to add something new without breaking old usage of `Faraday::UploadIO`.

**Comment by technoweenie** [comment]
Okay, I've looked into this a bit more, and I think I have a better handle on what's going on. Let me know if my understanding is off.

* Faraday param values can either be a string (or something easily convertable to one, such as an integer), or the values can be a `Faraday::UploadIO` (a reference to `::UploadIO` from the `multipart-post` gem.
* These values are just [thrown into `Faraday::Parts::Part.new`](https://github.com/lostisland/faraday/blob/f4ae96ea9b7850f0c2bf03a101b0d0beda8a1049/lib/faraday/request/multipart.rb#L54-L56) with no header. Note: `Faraday::Parts::Part` is a reference to `::Parts::Part` from the `multipart-post` gem.
* `::Parts::Part.new` checks [if the value responds to `#content_type` and `#local_filename`](https://github.com/socketry/multipart-post/blob/f119fc9739735ad4126e8edeaca1f292d039ba0c/lib/parts.rb#L18-L20). If so, it returns a `::Parts::FilePart`, which [uses the `UploadIO` object to get the value's content type](https://github.com/socketry/multipart-post/blob/f119fc9739735ad4126e8edeaca1f292d039ba0c/lib/parts.rb#L75-L76).
* Any values that aren't `UploadIO` are returned as a `::Parts::ParamPart`, which [needs its headers given explicitly](https://github.com/socketry/multipart-post/blob/f119fc9739735ad4126e8edeaca1f292d039ba0c/lib/parts.rb#L52-L61).

**Comment by jeremy-israel** [comment]
> Oh, I should've made this more clear. I'm not suggesting that `Faraday::UploadIO.new` is the answer here. My suggestion right now is more along the lines of:
> 
> ```ruby
> {
>   json_content: SOMETHING(json_content, 'application/json')
> }
> ```
> 
> I'm not sure what `SOMETHING` should be yet.

I gave it a thought. We could maybe create a class `Faraday::Parts::PartWithHeaders`. This class would be initialized with a string value and a headers hash.

In `Request::Multipart#create_multipart`, we could then create a `::Part` with the specified  headers from the `PartWithHeaders`.

Is that what you had in mind for the approach ? What do you think of the naming ? I also thought of `PartParams` instead.

**Comment by jeremy-israel** [comment]
I opened https://github.com/lostisland/faraday/pull/1017

**Pull request merged**
