### PR TITLE
Fix subclassing deprecated classes

### LINKED ISSUE #1033: Breaking change for octokit in 0.16.1
## Basic Info

* Faraday Version: 0.16.1
* Ruby Version: 2.6.4

## Issue description
Been having issues related to faraday with a new project using octokit.
```
~/.rvm/gems/ruby-2.6.4/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14:in `<module:Middleware>': superclass must be a Class (Faraday::DeprecatedConstant given) (TypeError)
```
Tested with 0.15.4 and there is no issue there.
If it is a desired breaking change then let me know, I will gladly report this to the octokit repository, maybe they will freeze faraday usage to a compatible version.

## Steps to reproduce
Create a new ruby file, install octokit, which will depends at some point on faraday latest, then at line `require octokit` this error will happen.

### PR DESCRIPTION
**Pull request by BobbyMcWho**
## Description

The previous implementation didn't work because it was setting the constant to an instance of `DeprecatedConstant` which wasn't a _class_, so therefore couldn't be subclassed. 

Feel free to critique my implementation and make any suggestions you see fit. 

Fixes #1033

### CODE REVIEW

**Comment by BobbyMcWho** [comment]
@technoweenie can you review this since the issues are trickling in

**Comment by BobbyMcWho** [comment]
@olleolleolle Squashed to 1 commit

**Comment by BobbyMcWho** [comment]
Updated the class doc

**Comment by olleolleolle** [comment]
Thanks for the repairs!

**Comment by BobbyMcWho** [comment]
@olleolleolle do you know when you're going to release this to rubygems?

**Comment by olleolleolle** [comment]
No, I don't know – currently traveling.

**Pull request merged**
