### PR TITLE
Proc auth value backport cleanup

### PR DESCRIPTION
**Pull request by iMacTia**
## Description
This PR is a follow-up to #1322 to adapt the implementation to the 1.x branch

cc @jarl-dk, who worked on the original PR 🙏

### CODE REVIEW

**Comment by iMacTia** [comment]
Not sure if this is a blip from Ubuntu packages or what, but I'm getting the following:

> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4-openssl-dev_7.68.0-1ubuntu2.6_amd64.deb
> 404  Not Found [IP: 52.147.219.192 80]

I'll try waiting a bit and then re-run tests. Good news is that they're all passing locally 🎉

**Comment by iMacTia** [comment]
And it's green 🟢 🎉 !

**Review by olleolleolle — APPROVED** [review]
This adapts the solution to be 1.x-ready. Thanks, everyone involved!

**Comment by jarl-dk** [comment]
Regarding ubuntu; It could be that it was a one-off server down issue.

**Comment by iMacTia** [comment]
Thanks for the review @olleolleolle 🎉!

@jarl-dk in case this might be useful, we were missing `apt-get update` before `install`, so it likely was an outdate package source 🤦‍♂️.

**Pull request merged**
