### PR TITLE
handle default connection options set with hash

### LINKED ISSUE #628: calling `url` on a `Hash` (NoMethodError)
faraday-0.10.0/lib/faraday/connection.rb:60 can now call url on a hash because of the changes on the line above it.

```
     Failure/Error: response = Faraday.new(url: gateway_url).run_request(*request_parameters)

     NoMethodError:
       undefined method `url' for #<Hash:0x007f757ad12f58>
     # ./vendor/bundle/ruby/gems/faraday-0.10.0/lib/faraday/connection.rb:63:in `initialize'
     # ./vendor/bundle/ruby/gems/faraday-0.10.0/lib/faraday.rb:74:in `new'
     # ./vendor/bundle/ruby/gems/faraday-0.10.0/lib/faraday.rb:74:in `new'
     # ./app/middleware/gateway_proxy.rb:24:in `proxy_response'
```

0.9.2:
```
        options = ConnectionOptions.from(url)
        url     = options.url
```

0.10.0:
```
        options = options ? options.merge(url) : ConnectionOptions.from(url)
        url     = options.url
```

Called with code:
`response = Faraday.new(url: gateway_url).run_request(*request_parameters)`

### PR DESCRIPTION
**Pull request by Cohen-Carlisle**
Fixes #628.

### CODE REVIEW

**Comment by iMacTia** [comment]
Hi @Cohen-Carlisle and thanks for your PR.
Would you mind adding some tests to your PR in order to double-check that all behaviours are still working? In particular, I would like the following to be carefully tested:

1. The following should now work **and be respected**:

```ruby
Faraday.default_connection_options = { request: { timeout: 0.0001 } }
Faraday.new(url: "http://www.example.com/").get("/")
```

2. The following should still work and be respected:

```ruby
Faraday.default_connection_options = { request: { timeout: 0.0001 } }
Faraday.new("http://www.example.com/").get("/")
```

3. We should allow to specify additional options when creating the connection (and check that these are respected):

```ruby
Faraday.default_connection_options = { request: { timeout: 0.0001 } }
Faraday.new("http://www.example.com/", { request: { open_timeout: 0.0001 }}).get("/")
# Same for Faraday.new(url: "http://www.example.com/", request: { open_timeout: 0.0001 }).get("/")
```

**Comment by Cohen-Carlisle** [comment]
I'll work on adding tests in.

**Comment by iMacTia** [comment]
Hi @Cohen-Carlisle , how are the test works going :)?

**Comment by Cohen-Carlisle** [comment]
My bad, got busy between work, play, and family. I will work on this tonight.

**Comment by Cohen-Carlisle** [comment]
@iMacTia while writing tests I discovered an interesting behavior with default vs object-specific connection options. In the last example you provided:
```ruby
Faraday.new("http://www.example.com/", { request: { open_timeout: 0.0001 }})
```
The `request` options in new overwrite any nested `request` options. E.g., either:
```ruby
Faraday.default_connection_options.request.timeout = 10
```
or 
```ruby
Faraday.default_connection_options = { request: { timeout: 10 } }
```
will lose the `request.timeout` setting. Basically, merges are not deep merges.

**Comment by Cohen-Carlisle** [comment]
I pushed up tests that should cover the cases requested, with the possible exception of the merge behavior described above.

**Comment by iMacTia** [comment]
That's unfortunately what I feared 😞
Question now is: was it working properly on 0.9.2?
I'll try to do the same there and see what happens, my feeling is that we just uncovered an old bug

**Comment by iMacTia** [comment]
Aaaaaaaand yes, we have an old bug.
But this will open up discussions like "what should I do to remove a default option for a single request?" and so on, so better to address it on a separate issue.
Thanks @Cohen-Carlisle. Great work, nice addition 👍

**Pull request merged**
