### PR TITLE
avoid argument warnings / prepare for ruby 3

### PR DESCRIPTION
**Pull request by grosser**
builds on top of https://github.com/lostisland/faraday/pull/1208
reverts https://github.com/lostisland/faraday/pull/1153 since 2.7 no longer has warnings and 3.0 works

### CODE REVIEW

**Comment by olleolleolle** [comment]
In order to go forward, I resolved the conflict in favor of the merged PR #1211

**Comment by grosser** [comment]
thx, there are some real bugs in here, (ran tests on 2.4 / 2.7 and no combination made both work)
so I think we need to either keep the dependency or do what it does in a simpler way :(

**Comment by olleolleolle** [comment]
@grosser Does this change your mind on #1211?

**Comment by olleolleolle** [comment]
@grosser Now I'm just messing with this, perhaps we can take a smaller step forwards trying to find working code. Grr, now I made a commit which predictably works on 2.7, but now the others. As you say, perhaps keeping the ruby2_keywords gem to support Olde Versions.

In addition, I noted that the coveralls gem is old and wonky, and I think I recall someone's actually shepherding it in a GitHub repo, somewhere. So, one _could_ use that gem, to avoid red output at the end of the test run.

**Comment by grosser** [comment]
Could also try https://github.com/grosser/single_cov :D

**Comment by iMacTia** [comment]
We support Ruby 3.0, 3.1 and 3.2 pretty well now so this should not be necessary anymore 👍

**Pull request closed without merging**
