### PR TITLE
Add Response#redirect? to check for HTTP 3xx

### PR DESCRIPTION
**Pull request by nathanl**
Added only the sort of test that currently exists for `success?` in an effort to conform to the project's current approach. I could add a test where `redirect?` is true if you like.

### CODE REVIEW

**Comment by nathanl** [comment]
Rebased on current master

**Comment by jirutka** [comment]
+1

**Comment by mislav** [comment]
Hey, thanks for the solid contribution! The code looks great but we decided not to pull this in since we don't believe that `redirect?` method is needed right now. Checking for redirects is not as easy as just checking for a 3xx status; if you wanted to follow a redirect you would have to check for a specific 3xx status, the "location" header, the request method and so much more.

**Comment by nathanl** [comment]
K, no worries. :)

**Pull request closed without merging**
