### PR TITLE
Bcarlson/http1 1 change to include body on deletes

### PR DESCRIPTION
**Pull request by Carlbc18**
These changes are to support HTTP 1.1 RFC https://tools.ietf.org/html/rfc7231 where HEAD, GET, DELETE all support a request body instead of merging request params into the url. For example on the delete (https://tools.ietf.org/html/rfc7231#section-4.3.5) the follow outlines the support for bodies: 

>  A payload within a DELETE request message has no defined semantics;
   sending a payload body on a DELETE request might cause some existing
   implementations to reject the request.

The same verbiage is used for HEAD and GET.  Please let me know if there is anything else, or if i completely messed things up (totally possible).

### CODE REVIEW

**Comment by iMacTia** [comment]
Hi @Carlbc18 and thanks for this contribution.
Now I understand what you meant by "breaking changes" 😄!
The biggest issue I can see with this approach is that it removes the possibility to easily set url parameters on GET, HEAD and DELETE requests, even though the HTTP standard now allows you to have both.

Ideally, we would like Faraday to allow setting both as easily as providing an hash to the request.
I understand this is not easy since we have a generic `params` parameter on this methods, but it would be great to have something like this:

Option 1: When you provide parameters to Faraday `#get`, `#head` or `#delete`, they go on the URL by default (backward compatibility) but you can optionally set them in the body. This can be achieved with a connection configuration as it's just a switch (either one or the other).

Option 2: Faraday provides the possibility to easily setup both, keeping backward compatibility.

As you can see backward compatibility is quite important as we're talking about 3 of the most important functions in Faraday 😅, so I would really love to have it even for v1.0.
That said, Option 2 would definitely be my favourite, but even option 1 would be OK to begin with.
And of course both options can be released before v1.0, assuming we have backward compatibility 😃 

Open to suggestions on how to implement either of them

**Comment by Carlbc18** [comment]
Hopefully it wasnt too scary of a change! I'm not very well versed in all of Faraday. I too like option 2 as a config option at object initialization. I might need some assistance in tracking down where everything is if you'd like me to make this change.

**Comment by iMacTia** [comment]
Not scary at all, actually I like the idea of embracing the new standard.
I simply want to maintain backward compatibility in doing so and possibly leave it as an option for developers.
I'd suggest we go back to the issue and discuss in there how we want this to work before continuing with the PR

**Comment by iMacTia** [comment]
Closing after discussion in https://github.com/lostisland/faraday/issues/693#issuecomment-305429333

**Pull request closed without merging**
