### PR TITLE
Streaming requests for Net::HTTP

### PR DESCRIPTION
**Pull request by jcoyne**
Based on work by @bmaddy, @james-lawrence and @ANorwell
https://github.com/backupify/faraday/tree/streaming-0.9.0
https://github.com/bmaddy/faraday/tree/streaming

### CODE REVIEW

**Comment by grosser** [comment]
can you fix up the build ?

@mislav any :heart: for this ? :)

**Comment by grosser** [comment]
only error I can reproduce locally is:

```
  1) Failure:
Adapters::NetHttpTest#test_GET_streaming [/Users/mgrosser/Code/tools/faraday/test/adapters/integration.rb:349]:
--- expected
+++ actual
@@ -1 +1 @@
-" !\"\#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~ !\"\#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~ !\"\#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`a"
+""
```

rest might be fixable by rebasing ...

**Comment by mislav** [comment]
This looks pretty impressive. Sorry for no review. @grosser you're welcome to try to rebase this branch against current master if @jcoyne isn't able to do it.

**Comment by grosser** [comment]
any idea how to run this 1 failing test ... rake passes locally when rebased and I did not find a way to execute just 1 test ... via `-n` or similar :(

**Comment by jcoyne** [comment]
I don't foresee having any time to work on this in the near future. All I did was to rebase the work done by others.

**Comment by nightscape** [comment]
@jcoyne I've created a rebased version of this PR in https://github.com/lostisland/faraday/pull/604 that also fixes the issue mentioned by @grosser.
Can you close this PR in favor of the above one?

**Comment by iMacTia** [comment]
Closing in favour of #604

**Comment by jcoyne** [comment]
@nightscape Thanks for picking this up. 👍

**Pull request closed without merging**
