### PR TITLE
avoid 1 use of keyword hackery

### PR DESCRIPTION
**Pull request by grosser**
based on https://github.com/lostisland/faraday/pull/1208
https://github.com/lostisland/faraday/pull/1209 has some funky errors, but this change at least seems to work on old and new ruby alike

### CODE REVIEW

**Comment by olleolleolle** [comment]
How I reviewed: I entered the Test tab of the ruby-head build target, then opened the tiny built-in search window, entered the word warning, and hit the arrow icon to navigate between the case-insensitive search hits. All of them were about other things.

This change _works_ on latest Ruby. 

Thanks, @grosser, for a meticulous fix!

**Comment by grosser** [comment]
rebased it for a clean merge

**Review by olleolleolle — APPROVED** [review]
LGTM

**Comment by olleolleolle** [comment]
@grosser Thank you!

**Pull request merged**
