### PR TITLE
WIP: Support for 'no_proxy' environment variable.

### PR DESCRIPTION
**Pull request by johnbellone**
These are fixes that @mislav suggest in #247 comments.

### CODE REVIEW

**Comment by ashphy** [comment]
:+1:

**Comment by aaron-lane** [comment]
:+1:

**Comment by ljromero** [comment]
@mislav Why not update the default_adapter to :excon to fix this issue?

**Comment by iMacTia** [comment]
Ok just noticed this PR and can see that many people are asking for this change to be merged!
Happy to review and merge as soon as tests are green.

@johnbellone any chance you can help community with this? Or if not please tell us, maybe there's a volunteer to finish the work 😃

**Comment by johnbellone** [comment]
I likely won't have time to do this in next few weeks. Anyone willing to take over?

Sent from my iPhone
JB

**Comment by olleolleolle** [comment]
I'd like to try doing this today.

**Comment by no1stunna** [comment]
What is the status for this issue right now?

**Comment by iMacTia** [comment]
Closing in favour of #658

**Pull request closed without merging**
