### PR TITLE
Mention the externl typhoeus adapter

### PR DESCRIPTION
**Pull request by philsturgeon**
With the outdated bundled typhoeus adapter being removed (https://github.com/lostisland/faraday/pull/715) it's a good time they bundle one with their own gem.

### CODE REVIEW

**Comment by philsturgeon** [comment]
Looks like you got some whitespace stripped from your README for free! You're welcome 😅

**Comment by olleolleolle** [comment]
@iMacTia This bit is now merge-ready, yeah?

**Comment by iMacTia** [comment]
@olleolleolle If @philsturgeon is going to work on this one to introduce tests for `Typhoeus` then we should rename the PR accordingly and I'll wait to review it

**Comment by iMacTia** [comment]
@philsturgeon Rather than renaming this branch I've decided to merge this is as a simple README fix.
Please open a new PR for introducing Typhoeus tests

**Comment by philsturgeon** [comment]
👍

**Pull request merged**
