### PR TITLE
Add test coverage for POST with Retry middleware

### PR DESCRIPTION
**Pull request by Nitrodist**
There was a fix put in bc82276 (#296) that preserved the body of a
POST request that was being retried in the Retry middleware.
Unfortunately, there was no test added that ensures that this
functionality continues to work.

This commit adds the test to ensure that it continues to work in the
future.

### CODE REVIEW

**Comment by kennethkalmer** [comment]
I had a quick look to help triage this, and it seems that rebasing this should not be a problem. I just wonder about changing `@explode` to `@response_handler` everywhere, it seems to only be a matter of taste. Since this PR I think one or two more tests got added, and they all stuck with `@explode`.

/cc @mislav @technoweenie @mike-bourgeous

**Comment by mislav** [comment]
Yeah, let's avoid the renames to keep the diff minimal.

**Comment by Nitrodist** [comment]
1 failure now for a failing test in master, it seems.

**Comment by mislav** [comment]
Thanks! I've cleaned this up further.

**Comment by Nitrodist** [comment]
:+1:

**Pull request closed without merging**
