### PR TITLE
CircleCI Contexts

### LINKED ISSUE #984: CodeClimate test reporter complains: needs CC_TEST_REPORTER_ID for fork PRs
CodeClimate test reporter complains: needs CC_TEST_REPORTER_ID

```
#!/bin/bash -eo pipefail
./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?

Error: you must supply a CC_TEST_REPORTER_ID ENV variable or pass it via the -r flag
Usage:
  cc-test-reporter after-build [flags]

Flags:
  -s, --batch-size int               batch size for source files (default 500)
  -e, --coverage-endpoint string     endpoint to upload coverage information to (default "https://api.codeclimate.com/v1/test_reports")
  -t, --coverage-input-type string   type of input source to use [clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, simplecov]
      --exit-code int                exit code of the test run
  -r, --id string                    reporter identifier
      --insecure                     send coverage insecurely (without HTTPS)
  -p, --prefix string                the root directory where the coverage analysis was performed (default "/home/circleci/project")

Global Flags:
  -d, --debug   run in debug mode

Exited with code 255
```

_Originally posted by @olleolleolle in https://github.com/lostisland/faraday/pull/983#issuecomment-495607748_

### PR DESCRIPTION
**Pull request by iMacTia**
## Description
Introduces the usage of CircleCI contexts to keep secrets safe.
Fixes #984

### CODE REVIEW

**Comment by olleolleolle** [comment]
Did you perhaps not change the YAML config, yet?

**Comment by iMacTia** [comment]
@olleolleolle yep, this was intentional 😄 I wanted to reproduce the issue on one of my forks first.
Now I'll try to fix it

**Comment by iMacTia** [comment]
Sooooooo, the context is there and the place is definitely the right one (I tried moving, but got a configuration error).
Still, the environment variable is not picked for some reason. Any ideas 😄 ?

**Comment by iMacTia** [comment]
Well, I should definitely have access, so I'm surprised to be honest. But even if I make it work, I don't think I can actually make it accessible for contributors.

I don't really understand what we're supposed to use here. I'd just like something like Travis' [Encrypted variables](https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml)

**Comment by iMacTia** [comment]
I gave up for now since `CC_TEST_REPORTER_ID` is not super-secret anyway, but we'll definitely need to solve this issue for Rubygems deployment 😞

**Pull request closed without merging**
