### PR TITLE
Resolve Layout/ElseAlignment Violations

### PR DESCRIPTION
**Pull request by jherdman**
## Description

Tick another box on #854

### CODE REVIEW

**Comment by technoweenie** [comment]
Hi @jherdman, thanks for taking a look at this! This PR doesn't actually fix all of the `Layout/ElseAlignment` offenses though, just the ones not excused by the [rubocop todo file](https://github.com/lostisland/faraday/blob/3a11286c8746e4e086729e60cc3cc1893060db8d/.rubocop_todo.yml#L27-L31).

This specific change fails on master because it looks like our CI process is not preventing merges properly. This PR fixes half of it, and #870 fixes the rest. I'd like to get our CI issues resolved before merging these though.

**Comment by jherdman** [comment]
Ah, snap. I didn't realize that file was there. I'll take a look at those too.

**Comment by technoweenie** [comment]
@jherdman I'm new to rubocop, so I'm trying to come up with a general workflow. I think it's:

1. Remove exceptions from `.rubocop_todo.yml`
2. Fix code
3. Run `bundle exec rubocop --auto-gen-config`
4. Commit, PR, Merge, Profit :metal:

Do you know if there's some way to run `rubocop --only=Layout/BlockEndNewline` while ignoring the todo file. I'm just trying to document the rubocop fix workflow.

**Comment by jherdman** [comment]
> Do you know if there's some way to run `rubocop --only=Layout/BlockEndNewline` while ignoring the todo file. I'm just trying to document the rubocop fix workflow

Sadly, no. I'm in the same boat as you w.r.t RuboCop.

I went back, though, and resolved the remaining ElseAlignment problems.

**Pull request merged**
