### PR TITLE
don't stomp on request body

### PR DESCRIPTION
**Pull request by lanej**
- store request_body in env
- allow response to contain all the information of the request

### CODE REVIEW

**Comment by iMacTia** [comment]
Waiting for anything before merging this? Looks like a great addition!

**Comment by lanej** [comment]
@iMacTia still waiting on the verdict

**Comment by iMacTia** [comment]
8 months later... 😕

**Comment by a0s** [comment]
2 years later ... :(

**Comment by iMacTia** [comment]
This is now being addressed as part of #845 and will be available in v1.0

**Pull request closed without merging**
