### PR TITLE
docs(website): add search to the website

### LINKED ISSUE #1110: Documentation should provide a clearer list of pages
## Basic Info

Even if I went multiple times to the website, I first completely missed the fact that there are actually more pages than the ones here:
image

For example I was looking for the retry documentation and could not find it but in GitHub, because to access it you need to do this:
1. Click on middleware
2. Click at the bottom for "Available middleware"
3. Click on the retry middleware

Step 2. is the easy one to miss because the link is not obvious.

I would propose to have something like this instead:

image

Or in general, a way to visualize easily all the documentation links without having to scroll down etc..

PS: I worked previously at Algolia, they provide this service for documentation websites: https://community.algolia.com/docsearch/. Would you like it implemented on the faraday website? I can help with that!

### PR DESCRIPTION
**Pull request by vvo**
## Description
This commit adds documentation search to the whole website using Algolia's
DocSearch project: https://community.algolia.com/docsearch/

I tried to be as close as the Faraday design as possible.

fixes #1110 (at least it provides an easy way to search for pages, even if pages are not clearly laid out in the navigation)

You can test the search here: https://faraday.codeagain.now.sh/

## Todos
List any remaining work that needs to be done, i.e:
- [ ] Get review from the Faraday team

## Additional Notes
It's possible to get analytics on the search feature: what is searched, what get no results (= need to document). I have access to all of that but if you maintainers want that too, just provide me your email address and I will invite you to the application. You will have to create an Algolia account.

### CODE REVIEW

**Comment by olleolleolle** [comment]
image
 
I entered _middleware_ and  saw things immediately. Wow!

**Comment by vvo** [comment]
> I entered _middleware_ and saw things immediately. Wow!

That's the Algolia magic and the awesome configuration from @s-pace!

**Comment by vvo** [comment]
I dunno why the tests are failing, do you know @olleolleolle?

**Comment by olleolleolle** [comment]
16 failures, all in adapter/rack_spec... Hm

```

rspec './spec/faraday/adapter/rack_spec.rb[1:1:1:3:1:1]' # Faraday::Adapter::Rack behaves like an adapter with SSL enabled #head behaves like a request method handles headers with multiple values
rspec './spec/faraday/adapter/rack_spec.rb[1:1:1:4:1:2]' # Faraday::Adapter::Rack behaves like an adapter with SSL enabled #options behaves like a request method handles headers with multiple values
rspec './spec/faraday/adapter/rack_spec.rb[1:1:1:8:1:2]' # Faraday::Adapter::Rack behaves like an adapter with SSL enabled #trace behaves like a request method handles headers with multiple values
rspec './spec/faraday/adapter/rack_spec.rb[1:1:1:1:1:2]' # Faraday::Adapter::Rack behaves like an adapter with SSL enabled #delete behaves like a request method handles headers with multiple values
rspec './spec/faraday/adapter/rack_spec.rb[1:1:1:6:1:2]' # Faraday::Adapter::Rack behaves like an adapter with SSL enabled #post behaves like a request method handles headers with multiple values
rspec './spec/faraday/adapter/rack_spec.rb[1:1:1:7:1:2]' # Faraday::Adapter::Rack behaves like an adapter with SSL enabled #put behaves like a request method handles headers with multiple values
rspec './spec/faraday/adapter/rack_spec.rb[1:1:1:2:1:2]' # Faraday::Adapter::Rack behaves like an adapter with SSL enabled #get behaves like a request method handles headers with multiple values
rspec './spec/faraday/adapter/rack_spec.rb[1:1:1:5:1:2]' # Faraday::Adapter::Rack behaves like an adapter with SSL enabled #patch behaves like a request method handles headers with multiple values
rspec './spec/faraday/adapter/rack_spec.rb[1:1:2:1:1:2]' # Faraday::Adapter::Rack behaves like an adapter with SSL disabled #delete behaves like a request method handles headers with multiple values
rspec './spec/faraday/adapter/rack_spec.rb[1:1:2:6:1:2]' # Faraday::Adapter::Rack behaves like an adapter with SSL disabled #post behaves like a request method handles headers with multiple values
rspec './spec/faraday/adapter/rack_spec.rb[1:1:2:5:1:2]' # Faraday::Adapter::Rack behaves like an adapter with SSL disabled #patch behaves like a request method handles headers with multiple values
rspec './spec/faraday/adapter/rack_spec.rb[1:1:2:8:1:2]' # Faraday::Adapter::Rack behaves like an adapter with SSL disabled #trace behaves like a request method handles headers with multiple values
rspec './spec/faraday/adapter/rack_spec.rb[1:1:2:7:1:2]' # Faraday::Adapter::Rack behaves like an adapter with SSL disabled #put behaves like a request method handles headers with multiple values
rspec './spec/faraday/adapter/rack_spec.rb[1:1:2:4:1:2]' # Faraday::Adapter::Rack behaves like an adapter with SSL disabled #options behaves like a request method handles headers with multiple values
rspec './spec/faraday/adapter/rack_spec.rb[1:1:2:3:1:1]' # Faraday::Adapter::Rack behaves like an adapter with SSL disabled #head behaves like a request method handles headers with multiple values
rspec './spec/faraday/adapter/rack_spec.rb[1:1:2:2:1:2]' # Faraday::Adapter::Rack behaves like an adapter with SSL disabled #get behaves like a request method handles headers with multiple values
```

**Comment by vvo** [comment]
Just to make sure, @iMacTia or @olleolleolle are you still interested in this? Maybe waiting for me to fix the build? Since I only changed documentation files, not sure why this would be failing :D

**Comment by olleolleolle** [comment]
@vvo We are very interested in the change, but are also snooping around for clues about the build failure. The 2.1.1 of rack has moved forwards, whereas rack-test has stood still. Perhaps something else is needed from our rack test set-up, now.

**Comment by vvo** [comment]
The weird thing is that master seems to be green ✔️. But on this PR it's just master with doc/ changes so that does not makes sense. Maybe there's  a glitch in the GitHub actions configuration? I could have a look at that if you want maybe.

**Comment by olleolleolle** [comment]
@vvo https://github.com/lostisland/faraday/actions?query=workflow%3ACI latest CI build on master was 12 days ago, rack releases have happened in between.

**Comment by vvo** [comment]
@olleolleolle Ohhh right, well it all depends on how and where we depend on Rack I guess. I am used to dependency pining to avoid such situations (at least if it's a dev-only direct dependency). So that your dev workflow is not blocked by a dependency that has no impact on the release of the library. 

I am definitely new to Ruby and coming from Node.js where yarn.lock files are used even in libraries to allow locking dev-dependencies only.

Good luck and let me know if you need help!

**Comment by olleolleolle** [comment]
I have catalogued the issue that breaks the build as #1119

**Comment by olleolleolle** [comment]
Thanks, @vvo, a lot, for giving us this present!

**Pull request merged**
