### PR TITLE
WebMock test example in README.md

### PR DESCRIPTION
**Pull request by omouse**
Added an example of how to stub requests in an RSpec test suite using WebMock: https://github.com/bblimke/webmock

Code based on examples found here:
* https://github.com/bblimke/webmock#setting-expectations-in-rspec-with-a_request
* https://github.com/bblimke/webmock#setting-expectations-in-rspec-on-the-stub

### CODE REVIEW

**Comment by sbleon** [comment]
@omouse I'm not sure Faraday should document how to use WebMock.

Maybe a more general statement about how to test your Faraday-based code would be appropriate. "To test your Faraday-based code, you can use any HTTP mocking library that works with your HTTP adapter of choice." We could include links to WebMock and VCR, or a link to https://www.ruby-toolbox.com/categories/mocking_web_requests.

**Comment by omouse** [comment]
@sbleon up to you, I'm good either way

**Comment by sbleon** [comment]
I prefer my approach 😉 . If WebMock's API changes, we shouldn't need to update our docs. So I'd rather point at them than try to document it ourselves.

**Comment by mislav** [comment]
Thanks for the contribution, but closing with the reason @sbleon outlined above.

**Pull request closed without merging**
